public enum GenMuzical {
    POP, ROCK, RAP, JAZZ, CLASIC, FOLK, ELECTRONICA, METAL, BLUES, REGGAE,
    COUNTRY, HIPHOP, DANCE, LATINO, PUNK, INDIE, ALTERNATIV, RHYTHM_AND_BLUES, SOUL, FUNK,
    GOSPEL, OPERA, TEATRU_MUZICAL, MUSICAL, FILM, ALTUL
}
